DROP TABLE ACCOUNT;
DROP SEQUENCE ACCOUNT_ID_SEQ;

DROP TABLE AC_CHARACTER;
DROP SEQUENCE CHARACTER_ID_SEQ;
DROP SEQUENCE ITEM_ID_SEQ START_WITH;

CREATE TABLE ACCOUNT (
	ACCOUNT_ID VARCHAR2(20) NOT NULL,
	ACCOUNT_PW VARCHAR2(30) NOT NULL,
	NAME VARCHAR2(20),
	HIREDATE DATE DEFAULT SYSDATE,
	ID VARCHAR2(4) PRIMARY KEY
);

CREATE TABLE AC_CHARACTER (
  USER_ID VARCHAR2(20),
  CH_ID VARCHAR2(20) PRIMARY KEY,
  CH_NAME VARCHAR2(20) NOT NULL,
  CH_CLASS VARCHAR2(20) NOT NULL,
  CH_LEVEL NUMBER(3) NOT NULL,
  CH_CUR_EXP NUMBER(12),
  HP NUMBER(9) NOT NULL,
  MP NUMBER(9) NOT NULL,
  CRITICAL NUMBER(3) NOT NULL,
  PHDAMAGE NUMBER(9) NOT NULL,
  ABDAMAGE NUMBER(9) NOT NULL,
  PHDEF NUMBER(9) NOT NULL,
  ABDEF NUMBER(9) NOT NULL,
  HITRATE NUMBER(3),
  EVASIONRATE NUMBER(2),
  STATUS_STR NUMBER(5) NOT NULL,
  STATUS_INT NUMBER(5) NOT NULL,
  STATUS_DEX NUMBER(5) NOT NULL,
  STATUS_LUCK NUMBER(5) NOT NULL,
  STATUS_POINT NUMBER(5) NOT NULL,
  SKILL_POINT NUMBER(5) NOT NULL,
  ELEMENT_DEF_WATER NUMBER(9),
  ELEMENT_DEF_EARTH NUMBER(9),
  ELEMENT_DEF_WIND NUMBER(9),
  ELEMENT_DEF_FIRE NUMBER(9),
  ELEMENT_ATK_WATER NUMBER(9),
  ELEMENT_ATK_EARTH NUMBER(9),
  ELEMENT_ATK_WIND NUMBER(9),
  ELEMENT_ATK_FIRE NUMBER(9),
  CREATED_DATE DATE,
  LAST_LOGOUT_DATE DATE,
  PLAY_TIME VARCHAR2(20),
  USER_STATUS VARCHAR2(50),
  CONSTRAINT USER_ID FOREIGN KEY(USER_ID) 
  REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE CH_INVENTORY_EQUIP (
  CH_ID VARCHAR2(20),
  ITEM_ID VARCHAR2(20) NOT NULL,
  ITEM_COUNT NUMBER(2) NOT NULL,
  INVEN_INDEX NUMBER(2) NOT NULL,
  CONSTRAINT CH_ID FOREIGN KEY(CH_ID)
    REFERENCES AC_CHARACTER(CH_ID) ON DELETE CASCADE
);

CREATE TABLE ITEM_EQUIP (
  ITEM_ID VARCHAR2(10) PRIMARY KEY,
  ITEM_TYPE VARCHAR2(20),
  ITEM_NAME VARCHAR2(20) NOT NULL,
  ITEM_DESC VARCHAR2(999) NOT NULL,
  BUY_PRICE NUMBER(20) NOT NULL,
  SELL_PRICE NUMBER(20) NOT NULL,
  EQUIP_LIMIT_LEVEL NUMBER(3),
  MAX_UPGRADE_COUNT NUMBER(2),
  MAX_NESTING_NUM NUMBER(2)
);

CREATE SEQUENCE CHARACTER_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ITEM_ID_SEQ START_WITH 1 INCREMENT BY 1;



CREATE SEQUENCE ACCOUNT_ID_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO ACCOUNT VALUES ('admin','123456' , '관리자', SYSDATE , ACCOUNT_ID_SEQ.NEXTVAL);

COMMIT;
