DROP TABLE ACCOUNT;
DROP SEQUENCE ACCOUNT_ID_SEQ;

CREATE TABLE ACCOUNT (
	ACCOUNT_ID VARCHAR2(20) NOT NULL,
	ACCOUNT_PW VARCHAR2(30) NOT NULL,
	NAME VARCHAR2(20),
	HIREDATE DATE DEFAULT SYSDATE,
	ID VARCHAR2(4) PRIMARY KEY
);

CREATE SEQUENCE ACCOUNT_ID_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO ACCOUNT VALUES ('admin','123456' , '°ü¸®ÀÚ', SYSDATE , ACCOUNT_ID_SEQ.NEXTVAL);

COMMIT;
